# Generated by Django 5.0.7 on 2025-11-02 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='concluida',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='data_conclusao',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='data_criacao',
        ),
    ]
