# Generated by Django 5.2.6 on 2025-10-01 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('objetivo', models.TextField()),
                ('tipo', models.CharField(choices=[('auxilio transporte', 'Auxílio transporte'), ('auxilio moradia', 'Auxílio moradia'), ('alimentação estudantil', 'Alimentação estudantil'), ('apoio a formação estudantil', 'Apoio a formação estudantil'), ('auxilios eventuais', 'Auxílios eventuais'), ('Outros', 'Outros')], default='auxilio transporte', max_length=30)),
                ('solicitados', models.CharField(choices=[('Todos', 'todos'), ('Todos inscritos no programa', 'todos inscritos no programa'), ('Selecionar alunos', 'selecionar alunos')], default='todos', max_length=30)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('total_formulario', models.IntegerField()),
                ('alunos_solicitados', models.IntegerField()),
                ('sem_resposta', models.IntegerField()),
            ],
            options={
                'db_table': 'formulario',
            },
        ),
        migrations.CreateModel(
            name='FormularioQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_pergunta', models.CharField(max_length=250)),
                ('tipo_pergunta', models.CharField(choices=[('paragrafo', 'Parágrafo'), ('multipla_escolha', 'Múltipla escolha'), ('caixa_selecao', 'Caixas de seleção')], default='multipla escolha', max_length=50)),
                ('obrigatoriedade', models.BooleanField()),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='conta_comigo_app.formulario')),
            ],
            options={
                'db_table': 'formulario_questao',
                'ordering': ['ordem'],
            },
        ),
    ]
